// export const brazilianStates = [
//     { "nome": "Acre", "sigla": "AC" },
//     { "nome": "Alagoas", "sigla": "AL" },
//     { "nome": "Amapá", "sigla": "AP" },
//     { "nome": "Amazonas", "sigla": "AM" },
//     { "nome": "Bahia", "sigla": "BA" },
//     { "nome": "Ceará", "sigla": "CE" },
//     { "nome": "Distrito Federal", "sigla": "DF" },
//     { "nome": "Espírito Santo", "sigla": "ES" },
//     { "nome": "Goiás", "sigla": "GO" },
//     { "nome": "Maranhão", "sigla": "MA" },
//     { "nome": "Mato Grosso", "sigla": "MT" },
//     { "nome": "Mato Grosso do Sul", "sigla": "MS" },
//     { "nome": "Minas Gerais", "sigla": "MG" },
//     { "nome": "Pará", "sigla": "PA" },
//     { "nome": "Paraíba", "sigla": "PB" },
//     { "nome": "Paraná", "sigla": "PR" },
//     { "nome": "Pernambuco", "sigla": "PE" },
//     { "nome": "Piauí", "sigla": "PI" },
//     { "nome": "Rio de Janeiro", "sigla": "RJ" },
//     { "nome": "Rio Grande do Norte", "sigla": "RN" },
//     { "nome": "Rio Grande do Sul", "sigla": "RS" },
//     { "nome": "Rondônia", "sigla": "RO" },
//     { "nome": "Roraima", "sigla": "RR" },
//     { "nome": "Santa Catarina", "sigla": "SC" },
//     { "nome": "São Paulo", "sigla": "SP" },
//     { "nome": "Sergipe", "sigla": "SE" },
//     { "nome": "Tocantins", "sigla": "TO" }

// ]

export const brazilianStates: string[] = [
    "AC",
    "AL",
    "AP",
    "AM",
    "BA",
    "CE",
    "DF",
    "ES",
    "GO",
    "MA",
    "MT",
    "MS",
    "MG",
    "PA",
    "PB",
    "PR",
    "PE",
    "PI",
    "RJ",
    "RN",
    "RS",
    "RO",
    "RR",
    "SC",
    "SP",
    "SE",
    "TO",
    // "AC",
    // "AL",
    // "ap",
    // "am",
    // "ba",
    // "ce",
    // "df",
    // "es",
    // "go",
    // "ma",
    // "mt",
    // "ms",
    // "mg",
    // "pa",
    // "pb",
    // "pr",
    // "pe",
    // "pi",
    // "rj",
    // "rn",
    // "rs",
    // "ro",
    // "rr",
    // "sc",
    // "sp",
    // "se",
    // "tp"
]